package vm

import (
	"fmt"
	"gibbon-lang/src/gibbon/code"
	"gibbon-lang/src/gibbon/compiler"
	"gibbon-lang/src/gibbon/object"
)

/*
 Virtual Machine Implementationf for the Gibbon Programming Language
 -------------------------------------------------------------------

 The Virtual Machine (VM) is responsible for executing the bytecode generated by the
 compiler. It maintains a stack-based architecture for efficient execution of instructions.

 Core Components:
 ---------------

 1. Constants
    - Stores all constant values from the bytecode
	- Referenced by instructions during execution
	- Immutable during VM execution

2. Instructions
   - Sequence of bytecode to execute
   - Each instruction consists of opcode and operands
   - Sequential execution model

3. Stack
   - Fixed size stack (2048 elements)
   - Used for operation operands and results
   - LIFO (Last In, First Out) structure

4. Stack Pointer
   - Points to next free slot in stack
   - Used for push/pop operations
   - Prevents stack overflow/underflow
*/

const StackSize = 2048

var True = &object.Boolean{Value: true}
var False = &object.Boolean{Value: false}

/*
Represents the virtual machine that executes bytecode.
It maintains the execution state including the instruction sequence, constant pool, and execnution stack.

Memory Layout:
-------------
Stack: [obj1][obj2][obj3][...][objN]

	         ^                      ^
			 |                      |
			 sp=0                  sp=N
*/
type VM struct {
	constants    []object.Object   // Constant pool from bytecode
	instructions code.Instructions // Instruction sequence to execute
	stack        []object.Object   // Fixed-size stack for operations
	sp           int               // Stack pointer (points to next free slot)
}

// Creates and intializes a new VM instance.
func New(bytecode *compiler.Bytecode) *VM {
	return &VM{
		instructions: bytecode.Instructions,
		constants:    bytecode.Constants,
		stack:        make([]object.Object, StackSize),
		sp:           0,
	}
}

/*
Executes the bytecode instructions sequentially.

Detailed Operation:
------------------
1. Instruction Processing
   - Uses instruction pointer (ip) to track current instruction
   - Decodes opcode from the current instruction
   - Handles different opcodes via switch statement

2. OpConstant Handling
   - Reads 2 bytes constant index
   - Retrieves constant from pool
   - Pushes constant onto stack

Example flow:
-----------
For OpConstant 256:
1. Read opcode
2. Read constant index (256)
3. Push constants[256] to stack
*/

func (vm *VM) Run() error {
	for ip := 0; ip < len(vm.instructions); ip++ {
		// Decode current opcode
		op := code.Opcode(vm.instructions[ip])

		switch op {
		case code.OpConstant:
			// Read 2-byte constant index
			constIndex := code.ReadUint16(vm.instructions[ip+1:])
			// Skip past the 2 bytes we just read, the next iteration of the loop
			// starts with "ip" pointing to an opcode instead of an operand.
			ip += 2

			// Push constant onto stack
			err := vm.push(vm.constants[constIndex])
			if err != nil {
				return err
			}

		case code.OpAdd, code.OpSub, code.OpMul, code.OpDiv:
			err := vm.executeBinaryOperation(op)
			if err != nil {
				return err
			}

		case code.OpPop:
			vm.pop()

		case code.OpTrue:
			err := vm.push(True)
			if err != nil {
				return err
			}

		case code.OpFalse:
			err := vm.push(False)
			if err != nil {
				return err
			}
		}

	}

	return nil
}

func (vm *VM) executeBinaryOperation(op code.Opcode) error {
	right := vm.pop()
	left := vm.pop()
	leftType := left.Type()
	rightType := right.Type()

	if leftType == object.INTEGER_OBJ && rightType == object.INTEGER_OBJ {
		return vm.executeBinaryIntegerOperation(op, left, right)
	}

	return fmt.Errorf("unsupported types for binary operation: %s %s", leftType, rightType)
}

func (vm *VM) executeBinaryIntegerOperation(op code.Opcode, left, right object.Object) error {
	leftValue := left.(*object.Integer).Value
	rightValue := right.(*object.Integer).Value

	var result int64

	switch op {
	case code.OpAdd:
		result = leftValue + rightValue
	case code.OpSub:
		result = leftValue - rightValue
	case code.OpMul:
		result = leftValue * rightValue
	case code.OpDiv:
		result = leftValue / rightValue
	default:
		return fmt.Errorf("unknown integer operator: %d", op)
	}

	return vm.push(&object.Integer{Value: result})
}

// Adds an object to the top of the stack.
func (vm *VM) push(obj object.Object) error {
	if vm.sp >= StackSize {
		return fmt.Errorf("stack overflow")
	}
	vm.stack[vm.sp] = obj
	vm.sp++

	return nil
}

// Returns the object at the top of the stack without removing it.
func (vm *VM) StackTop() object.Object {
	if vm.sp == 0 {
		return nil
	}

	return vm.stack[vm.sp-1]
}

func (vm *VM) pop() object.Object {
	o := vm.stack[vm.sp-1]
	vm.sp--
	return o
}

func (vm *VM) LastPoppedStackElem() object.Object {
	return vm.stack[vm.sp]
}
