package vm

import (
	"fmt"
	"gibbon-lang/src/gibbon/code"
	"gibbon-lang/src/gibbon/compiler"
	"gibbon-lang/src/gibbon/object"
)

/*
 Virtual Machine Implementationf for the Gibbon Programming Language
 -------------------------------------------------------------------

 The Virtual Machine (VM) is responsible for executing the bytecode generated by the
 compiler. It maintains a stack-based architecture for efficient execution of instructions.

 Core Components:
 ---------------

 1. Constants
    - Stores all constant values from the bytecode
	- Referenced by instructions during execution
	- Immutable during VM execution

2. Instructions
   - Sequence of bytecode to execute
   - Each instruction consists of opcode and operands
   - Sequential execution model

3. Stack
   - Fixed size stack (2048 elements)
   - Used for operation operands and results
   - LIFO (Last In, First Out) structure

4. Stack Pointer
   - Points to next free slot in stack
   - Used for push/pop operations
   - Prevents stack overflow/underflow
*/

const StackSize = 2048
const GlobalSize = 65536
const MaxFrames = 1024

var True = &object.Boolean{Value: true}
var False = &object.Boolean{Value: false}
var Null = &object.Null{}

/*
Represents the virtual machine that executes bytecode.
It maintains the execution state including the instruction sequence, constant pool, and execnution stack.

Memory Layout:
-------------
Stack: [obj1][obj2][obj3][...][objN]

	         ^                      ^
			 |                      |
			 sp=0                  sp=N
*/
type VM struct {
	constants []object.Object // Constant pool from bytecode
	// instructions code.Instructions // Instruction sequence to execute
	stack       []object.Object // Fixed-size stack for operations
	sp          int             // Stack pointer (points to next free slot)
	globals     []object.Object
	frames      []*Frame
	framesIndex int
}

// Creates and intializes a new VM instance.
func New(bytecode *compiler.Bytecode) *VM {
	mainFn := &object.CompiledFunction{Instructions: bytecode.Instructions}
	mainClosure := &object.Closure{Fn: mainFn}
	mainFrame := NewFrame(mainClosure, 0)

	frames := make([]*Frame, MaxFrames)
	frames[0] = mainFrame

	return &VM{
		// instructions: bytecode.Instructions,
		constants:   bytecode.Constants,
		stack:       make([]object.Object, StackSize),
		sp:          0,
		globals:     make([]object.Object, GlobalSize),
		frames:      frames,
		framesIndex: 1,
	}
}

func NewWithGlobalsStore(bytecode *compiler.Bytecode, s []object.Object) *VM {
	vm := New(bytecode)
	vm.globals = s
	return vm
}

/*
Executes the bytecode instructions sequentially.

Detailed Operation:
------------------
1. Instruction Processing
   - Uses instruction pointer (ip) to track current instruction
   - Decodes opcode from the current instruction
   - Handles different opcodes via switch statement

2. OpConstant Handling
   - Reads 2 bytes constant index
   - Retrieves constant from pool
   - Pushes constant onto stack

Example flow:
-----------
For OpConstant 256:
1. Read opcode
2. Read constant index (256)
3. Push constants[256] to stack
*/

func (vm *VM) Run() error {
	var ip int
	var ins code.Instructions
	var op code.Opcode

	for vm.currentFrame().ip < len(vm.currentFrame().Instructions())-1 {
		vm.currentFrame().ip++

		ip = vm.currentFrame().ip
		ins = vm.currentFrame().Instructions()

		// Decode current opcode
		op = code.Opcode(ins[ip])

		switch op {
		case code.OpConstant:
			// Read 2-byte constant index
			constIndex := code.ReadUint16(ins[ip+1:])
			// Skip past the 2 bytes we just read, the next iteration of the loop
			// starts with "ip" pointing to an opcode instead of an operand.
			vm.currentFrame().ip += 2

			// Push constant onto stack
			err := vm.push(vm.constants[constIndex])
			if err != nil {
				return err
			}

		case code.OpAdd, code.OpSub, code.OpMul, code.OpDiv:
			err := vm.executeBinaryOperation(op)
			if err != nil {
				return err
			}

		case code.OpEqual, code.OpNotEqual, code.OpGreaterThan:
			err := vm.executeComparison(op)
			if err != nil {
				return err
			}

		case code.OpPop:
			vm.pop()

		case code.OpArray:
			// Read 2-byte element count
			numElements := int(code.ReadUint16(ins[ip+1:]))
			// Skip past the 2-byte operand
			vm.currentFrame().ip += 2

			// Build array from top N elements
			array := vm.buildArray(vm.sp-numElements, vm.sp)
			// Adjust stack pointer to remove used elements
			vm.sp = vm.sp - numElements

			// Push the new array onto stack
			err := vm.push(array)
			if err != nil {
				return err
			}

		case code.OpTrue:
			err := vm.push(True)
			if err != nil {
				return err
			}

		case code.OpBang:
			err := vm.executeBangOperator()
			if err != nil {
				return err
			}

		case code.OpMinus:
			err := vm.executeMinusOperator()
			if err != nil {
				return err
			}

		case code.OpFalse:
			err := vm.push(False)
			if err != nil {
				return err
			}

		case code.OpJump:
			// Decodes the operand located right after the opcode
			pos := int(code.ReadUint16(ins[ip+1:]))
			// Set the ip to the target of our jump
			vm.currentFrame().ip = pos - 1

		case code.OpJumpNotTruthy:
			pos := int(code.ReadUint16(ins[ip+1:]))
			vm.currentFrame().ip += 2

			condition := vm.pop()
			if !isTruthy(condition) {
				vm.currentFrame().ip = pos - 1
			}

		case code.OpSetGlobal:
			// Read 2-byte global index operand
			globalIndex := code.ReadUint16(ins[ip+1:])
			// Skip past the 2-byte operand
			vm.currentFrame().ip += 2

			// Pop value from stack and store in globals array at index
			vm.globals[globalIndex] = vm.pop()

		case code.OpGetGlobal:
			// Read 2-byte global index operand
			globalIndex := code.ReadUint16(ins[ip+1:])
			// Skip past the 2-byte operand
			vm.currentFrame().ip += 2

			// Push global value onto stack
			err := vm.push(vm.globals[globalIndex])
			if err != nil {
				return err
			}

		case code.OpSetLocal:
			// Read 1-byte local index operand
			localIndex := code.ReadUint8(ins[ip+1:])
			// Skip past the 1-byte operand
			vm.currentFrame().ip += 1

			// Get the current frame
			frame := vm.currentFrame()

			// Compute the location of the local binding and then save the popped value off the stack
			// - Add the 'basePointer' to the index of the binding in question to get the computed location
			vm.stack[frame.basePointer+int(localIndex)] = vm.pop()

		case code.OpGetLocal:
			localIndex := code.ReadUint8(ins[ip+1:])
			vm.currentFrame().ip += 1

			frame := vm.currentFrame()

			err := vm.push(vm.stack[frame.basePointer+int(localIndex)])
			if err != nil {
				return err
			}

		case code.OpHash:
			numElements := int(code.ReadUint16(ins[ip+1:]))
			vm.currentFrame().ip += 2

			// Build hash from top N elements (N = numElements)
			hash, err := vm.buildHash(vm.sp-numElements, vm.sp)
			if err != nil {
				return err
			}

			// Remove used elements and push hash
			vm.sp = vm.sp - numElements
			err = vm.push(hash)
			if err != nil {
				return err
			}

		case code.OpIndex:
			index := vm.pop()
			left := vm.pop()

			err := vm.executeIndexExpression(left, index)
			if err != nil {
				return err
			}

		case code.OpNull:
			err := vm.push(Null)
			if err != nil {
				return err
			}

		case code.OpCall:
			// Implements function invocation
			numArgs := code.ReadUint8(ins[ip+1:])
			vm.currentFrame().ip += 1

			err := vm.executeCall(int(numArgs))
			if err != nil {
				return err
			}

		case code.OpReturnValue:
			// Implements function return with value

			// Pop return value from stack
			returnValue := vm.pop()

			// Remove current frame
			frame := vm.popFrame()
			// Removes the local bindings
			vm.sp = frame.basePointer - 1

			// Push return value on caller's stack
			err := vm.push(returnValue)
			if err != nil {
				return err
			}

		case code.OpReturn:
			// Remove current frame
			frame := vm.popFrame()
			// Removes the local bindings
			vm.sp = frame.basePointer - 1

			err := vm.push(Null)
			if err != nil {
				return err
			}

		case code.OpGetBuiltin:
			builtinIndex := code.ReadUint8(ins[ip+1:])
			vm.currentFrame().ip += 1

			definition := object.Builtins[builtinIndex]

			err := vm.push(definition.Builtin)
			if err != nil {
				return err
			}

		case code.OpClosure:
			constIndex := code.ReadUint16(ins[ip+1:])
			numFree := code.ReadUint8(ins[ip+3:])
			vm.currentFrame().ip += 3

			err := vm.pushClosure(int(constIndex), int(numFree))
			if err != nil {
				return err
			}

		case code.OpGetFree:
			// Reads the index of the free variable from the instruction
			// This index corresponds to the position in the closure's free variables array
			freeIndex := code.ReadUint8(ins[ip+1:])
			vm.currentFrame().ip += 1

			// Get the current closure being executed from the current frame
			currentClosure := vm.currentFrame().cl

			// Push the free variable onto the stack
			err := vm.push(currentClosure.Free[freeIndex])
			if err != nil {
				return err
			}

		case code.OpCurrentClosure:
			currentClosure := vm.currentFrame().cl
			err := vm.push(currentClosure)
			if err != nil {
				return err
			}
		}

	}

	return nil
}

func (vm *VM) executeBinaryOperation(op code.Opcode) error {
	right := vm.pop()
	left := vm.pop()
	leftType := left.Type()
	rightType := right.Type()

	if leftType == object.INTEGER_OBJ && rightType == object.INTEGER_OBJ {
		return vm.executeBinaryIntegerOperation(op, left, right)
	}

	if leftType == object.STRING_OBJ && rightType == object.STRING_OBJ {
		return vm.executeBinaryStringOperation(op, left, right)
	}

	return fmt.Errorf("unsupported types for binary operation: %s %s", leftType, rightType)
}

func (vm *VM) executeComparison(op code.Opcode) error {
	right := vm.pop()
	left := vm.pop()

	if left.Type() == object.INTEGER_OBJ && right.Type() == object.INTEGER_OBJ {
		return vm.executeIntegerComparison(op, left, right)
	}

	switch op {
	case code.OpEqual:
		return vm.push(nativeBoolToBooleanObject(right == left))
	case code.OpNotEqual:
		return vm.push(nativeBoolToBooleanObject(right != left))
	default:
		return fmt.Errorf("unknown operator: %d (%s %s)", op, left.Type(), right.Type())
	}
}

func (vm *VM) executeIntegerComparison(op code.Opcode, left, right object.Object) error {
	leftValue := left.(*object.Integer).Value
	rightValue := right.(*object.Integer).Value

	switch op {
	case code.OpEqual:
		return vm.push(nativeBoolToBooleanObject(rightValue == leftValue))
	case code.OpNotEqual:
		return vm.push(nativeBoolToBooleanObject(rightValue != leftValue))
	case code.OpGreaterThan:
		return vm.push(nativeBoolToBooleanObject(leftValue > rightValue))
	default:
		return fmt.Errorf("unknown operator: %d", op)
	}
}

func nativeBoolToBooleanObject(input bool) *object.Boolean {
	if input {
		return True
	}

	return False
}

func (vm *VM) executeBinaryIntegerOperation(op code.Opcode, left, right object.Object) error {
	leftValue := left.(*object.Integer).Value
	rightValue := right.(*object.Integer).Value

	var result int64

	switch op {
	case code.OpAdd:
		result = leftValue + rightValue
	case code.OpSub:
		result = leftValue - rightValue
	case code.OpMul:
		result = leftValue * rightValue
	case code.OpDiv:
		result = leftValue / rightValue
	default:
		return fmt.Errorf("unknown integer operator: %d", op)
	}

	return vm.push(&object.Integer{Value: result})
}

func (vm *VM) executeBinaryStringOperation(op code.Opcode, left, right object.Object) error {
	if op != code.OpAdd {
		return fmt.Errorf("unknown string operator: %d", op)
	}

	leftValue := left.(*object.String).Value
	rightValue := right.(*object.String).Value

	return vm.push(&object.String{Value: leftValue + rightValue})
}

func (vm *VM) executeBangOperator() error {
	operand := vm.pop()

	switch operand {
	case True:
		return vm.push(False)
	case False:
		return vm.push(True)
	case Null:
		return vm.push(True)
	default:
		return vm.push(False)
	}
}

func (vm *VM) executeMinusOperator() error {
	operand := vm.pop()

	if operand.Type() != object.INTEGER_OBJ {
		return fmt.Errorf("unsupported type for negation: %s", operand.Type())
	}

	value := operand.(*object.Integer).Value
	return vm.push(&object.Integer{Value: -value})
}

func (vm *VM) executeIndexExpression(left, index object.Object) error {
	switch {
	case left.Type() == object.ARRAY_OBJ && index.Type() == object.INTEGER_OBJ:
		return vm.executeArrayIndex(left, index)
	case left.Type() == object.HASH_OBJ:
		return vm.executeHashIndex(left, index)
	default:
		return fmt.Errorf("index operator not supported: %s", left.Type())
	}
}

func (vm *VM) executeArrayIndex(array, index object.Object) error {
	arrayObject := array.(*object.Array)
	i := index.(*object.Integer).Value
	max := int64(len(arrayObject.Elements) - 1)

	if i < 0 || i > max {
		return vm.push(Null)
	}

	return vm.push(arrayObject.Elements[i])
}

func (vm *VM) executeHashIndex(hash, index object.Object) error {
	hashObject := hash.(*object.Hash)

	key, ok := index.(object.Hashable)
	if !ok {
		return fmt.Errorf("unusable as hash key: %s", index.Type())
	}
	pair, ok := hashObject.Pairs[key.HashKey()]
	if !ok {
		return vm.push(Null)
	}
	return vm.push(pair.Value)
}

// Creates a new array object from stack elements
// Parameters:
// - startIndex: Start of elements to include
// - endIndex:   End of elements to include
// Returns: New array object
func (vm *VM) buildArray(startIndex, endIndex int) object.Object {
	// Create a slice to hild array elements
	elements := make([]object.Object, endIndex-startIndex)

	// Copy elements from stack to arrray
	for i := startIndex; i < endIndex; i++ {
		elements[i-startIndex] = vm.stack[i]
	}

	return &object.Array{Elements: elements}
}

// Creates a new hash object from stack elements
// Parameters:
// - startIndex: Start of key-value pairs to include
// - endIndex:   End of key-value pairs
// Returns:
// - New Hash object or error if keys are'nt hashable
func (vm *VM) buildHash(startIndex, endIndex int) (object.Object, error) {
	// Initialize hash map to store pairs
	hashedPairs := make(map[object.HashKey]object.HashPair)

	// Process stack elements as key-value pairs
	for i := startIndex; i < endIndex; i += 2 {
		key := vm.stack[i]
		value := vm.stack[i+1]

		// Create pair structure
		pair := object.HashPair{Key: key, Value: value}

		// Ensure key is hashable
		hashKey, ok := key.(object.Hashable)
		if !ok {
			return nil, fmt.Errorf("unusable as hash key: %s", key.Type())
		}

		// Store pair in hash map
		hashedPairs[hashKey.HashKey()] = pair
	}

	return &object.Hash{Pairs: hashedPairs}, nil
}

// Adds an object to the top of the stack.
func (vm *VM) push(obj object.Object) error {
	if vm.sp >= StackSize {
		return fmt.Errorf("stack overflow")
	}
	vm.stack[vm.sp] = obj
	vm.sp++

	return nil
}

// Returns the object at the top of the stack without removing it.
func (vm *VM) StackTop() object.Object {
	if vm.sp == 0 {
		return nil
	}

	return vm.stack[vm.sp-1]
}

func (vm *VM) executeCall(numArgs int) error {
	callee := vm.stack[vm.sp-1-numArgs]

	switch callee := callee.(type) {
	case *object.Closure:
		return vm.callClosure(callee, numArgs)
	case *object.Builtin:
		return vm.callBuiltin(callee, numArgs)
	default:
		return fmt.Errorf("calling non-function and non-built-in")
	}
}

// Sets up and executes a function call
// Parameters:
// - numArgs: Number of arguments being passed to function
// Returns: Error if function call setup fails
func (vm *VM) callClosure(cl *object.Closure, numArgs int) error {
	if numArgs != cl.Fn.NumParameters {
		return fmt.Errorf("wrong number of arguments: want=%d, got=%d", cl.Fn.NumParameters, numArgs)
	}

	// Create new frame for function execution
	// basePointer points to first argument in the block
	frame := NewFrame(cl, vm.sp-numArgs)
	vm.pushFrame(frame)

	// Adjust stack pointer to accomodate local variables
	vm.sp = frame.basePointer + cl.Fn.NumLocals

	return nil
}

// Creates a new closure object and pushes it onto the stack
// This method is crucial for implementing closures/functions that can access variables from their
// enclosing scopes.
// Parameters:
// - constIndex: Index into the constants pool where the compiledFunction is stored
// - numFree: Number of free variables the closure needs to capture
func (vm *VM) pushClosure(constIndex, numFree int) error {
	// Get the function from constants pool
	constant := vm.constants[constIndex]
	// Ensure it's actually a function
	function, ok := constant.(*object.CompiledFunction)

	if !ok {
		return fmt.Errorf("not a function: %+v", constant)
	}

	// Create slice to hold free variables
	free := make([]object.Object, numFree)

	// Copy free variables from stack
	for i := 0; i < numFree; i++ {
		free[i] = vm.stack[vm.sp-numFree+i]
	}
	// Adjust stack pointer to remove captured variables
	vm.sp = vm.sp - numFree

	// Create and push new closure object
	closure := &object.Closure{Fn: function, Free: free}

	return vm.push(closure)
}

// Responsible for executing built-in functions in the VM. It handles the mechanics
// of calling predefined functions that are part of the language's standard library.
func (vm *VM) callBuiltin(builtin *object.Builtin, numArgs int) error {
	// Extract arguments for the builting function.
	args := vm.stack[vm.sp-numArgs : vm.sp]

	// Call the builtin function by passing all arguments
	result := builtin.Fn(args...)
	// Adjust the stack pointer to remove the arguments and function from stack.
	// Subtract numArgs to remove the arguments and an additional 1 to remove the function.
	vm.sp = vm.sp - numArgs - 1

	if result != nil {
		vm.push(result)
	} else {
		vm.push(Null)
	}

	return nil
}

func (vm *VM) pop() object.Object {
	o := vm.stack[vm.sp-1]
	vm.sp--
	return o
}

func (vm *VM) LastPoppedStackElem() object.Object {
	return vm.stack[vm.sp]
}

func isTruthy(obj object.Object) bool {
	switch obj := obj.(type) {
	case *object.Boolean:
		return obj.Value
	case *object.Null:
		return false
	default:
		return true
	}
}

func (vm *VM) currentFrame() *Frame {
	return vm.frames[vm.framesIndex-1]
}

func (vm *VM) pushFrame(f *Frame) {
	vm.frames[vm.framesIndex] = f
	vm.framesIndex++
}

func (vm *VM) popFrame() *Frame {
	vm.framesIndex--
	return vm.frames[vm.framesIndex]
}
