package compiler

import (
	"fmt"
	"gibbon-lang/src/gibbon/ast"
	"gibbon-lang/src/gibbon/code"
	"gibbon-lang/src/gibbon/object"
	"sort"
)

/*
Compiler Implementation for the Gibbon Programming Language
-----------------------------------------------------------

This file implements the compiler that transforms AST nodes into bytecode.
The compiler acts a bridge between the parser and virtual machine, converting
high-level syntax into efficient bytecode instructions.

Key Components:
--------------

1. Compiler Structure
   - Maintains instruction sequence
   - Manages constant pool
   - Handles symbol table

2. Bytecode Structure
   - Stores compiled instructions
   - Contains constant pool
   - Ready for VM execution

3. Compilation Process
   - Walks the AST
   - Generates appropriate bytecode
   - Manages constants and symbols
*/

type EmittedInstruction struct {
	OpCode   code.Opcode
	Position int
}

// Represents a single scope during compilation
// It maintains state for a specific compilation context (e.g., function body, global scope)
type CompilationScope struct {
	instructions        code.Instructions  // Holds the bytecode sequence for this scope
	lastInstruction     EmittedInstruction // Tracks the most recently emmitted instruction
	previousInstruction EmittedInstruction // Track the second-to-last instruction
}

// Compiler transforms AST nodes into bytecode instructions.
// It maintains state during the compilation process including genrated
// instructions and constants/
type Compiler struct {
	instructions code.Instructions // Holds the generated bytecode sequence
	constants    []object.Object   // Stores all constant values encountered during compilation
	symbolTable  *SymbolTable
	scopes       []CompilationScope
	scopeIndex   int
}

// Represents the final output of compilation
// It contains everything the VM needs to execute the program.
type Bytecode struct {
	Instructions code.Instructions // The sequence of bytecode instructions
	Constants    []object.Object   // The constant pool containing all constant values referenced by the instructions
}

// Creates and inits a new Compiler instance
func New() *Compiler {
	mainScope := CompilationScope{
		instructions:        code.Instructions{},
		lastInstruction:     EmittedInstruction{},
		previousInstruction: EmittedInstruction{},
	}
	return &Compiler{
		constants:   []object.Object{},
		symbolTable: NewSymbolTable(),
		scopes:      []CompilationScope{mainScope},
		scopeIndex:  0,
	}
}

func NewWithState(s *SymbolTable, constants []object.Object) *Compiler {
	compiler := New()
	compiler.symbolTable = s
	compiler.constants = constants
	return compiler
}

/*
Processes an AST node and generates corresponding bytecode instructions.
This is the core compilation method that walks through the AST and transforms high-level
language constructs into low-level bytecode operations.

Detailed Operation:
------------------
1. AST Traversal
  - Uses type switches for different node types
  - Recursively processes nested nodes
  - Maintains correct evaluation order

2. Code Generation:
  - Emits appropriate bytecode instructions
  - Manages constant pool entries
  - Preserves expression semantics

3. Error Handling
  - Propagates errors up the compilation chain
  - Ensures partial compilation results are valid
  - Prevents invalid bytecode generation

Parameters:

	node:  The AST node to compile

Returns:

	error: Any error encountered during compilation

Example Flow:
------------
For expression "1" + "2":
1. Compile left(1):
  - Add 1 to constant pool
  - Emit OpConstant for 1

2. Compile right(2):
  - Add 2 to constant pool
  - Emit OpConstant for 2
*/
func (c *Compiler) Compile(node ast.Node) error {
	switch node := node.(type) {
	case *ast.Program:
		// Process each statement in the program sequentially
		for _, s := range node.Statements {
			err := c.Compile(s)
			if err != nil {
				return err
			}
		}

	case *ast.ExpressionStatement:
		// Compile the expression within the statement
		err := c.Compile(node.Expression)
		if err != nil {
			return err
		}
		c.emit(code.OpPop)

	case *ast.ArrayLiteral:
		for _, el := range node.Elements {
			err := c.Compile(el)
			if err != nil {
				return err
			}
		}

		c.emit(code.OpArray, len(node.Elements))

	case *ast.HashLiteral:
		// Extract keys
		keys := []ast.Expression{}
		for k := range node.Pairs {
			keys = append(keys, k)
		}

		// Sort keys for consistent hash layout
		sort.Slice(keys, func(i, j int) bool {
			return keys[i].String() < keys[j].String()
		})

		// Compile key-value pairs
		// For each pair, compile both key and value
		// Stack layout after each pair: [..., key1, val1, key2, val2]
		for _, k := range keys {
			// Compile key
			err := c.Compile(k)
			if err != nil {
				return err
			}

			// Compile corresponding value
			err = c.Compile(node.Pairs[k])
			if err != nil {
				return err
			}
		}

		// Emit hash construction instruction
		// OpHash takes number of key-value pairs * 2 as operand
		// This tells VM how many stack items to consume
		c.emit(code.OpHash, len(node.Pairs)*2)

	case *ast.LetStatement:
		err := c.Compile(node.Value)
		if err != nil {
			return err
		}

		symbol := c.symbolTable.Define(node.Name.Value)

		if symbol.Scope == GlobalScope {
			c.emit(code.OpSetGlobal, symbol.Index)
		} else {
			c.emit(code.OpSetLocal, symbol.Index)
		}

	case *ast.Identifier:
		symbol, ok := c.symbolTable.Resolve(node.Value)
		if !ok {
			return fmt.Errorf("undefined variable %s", node.Value)
		}
		if symbol.Scope == GlobalScope {
			c.emit(code.OpGetGlobal, symbol.Index)
		} else {
			c.emit(code.OpGetLocal, symbol.Index)
		}
	case *ast.Boolean:
		if node.Value {
			c.emit(code.OpTrue)
		} else {
			c.emit(code.OpFalse)
		}

	case *ast.StringLiteral:
		str := &object.String{Value: node.Value}
		c.emit(code.OpConstant, c.addConstant(str))
	case *ast.IfExpression:
		// 1. Compile the condition expression
		// This will leave the condition's result on top of the stack
		err := c.Compile(node.Condition)
		if err != nil {
			return err
		}

		// Emit jump instruction for ƒalse condition
		// We use a placeholder jump offset(9999) that will be backpatched later
		// This implements the branching behavior of if statements
		jumpNotTruthyPos := c.emit(code.OpJumpNotTruthy, 9999)

		// 3. Compile the conseqeunce (true branch)
		err = c.Compile(node.Consequence)
		if err != nil {
			return err
		}

		// 4. Remove unnecessary OpPop if present
		// This preserces the last value in conditional blocks
		if c.lastInstructionIs(code.OpPop) {
			c.removeLastPop()
		}

		// 5. Step unconditional jump
		// Skip over else block after executing consequence
		jumpPos := c.emit(code.OpJump, 9999)

		// 6. Update conditional jump target
		// Now we know where the else block starts
		afterConsequencePos := len(c.currentInstructions())
		c.changeOperand(jumpNotTruthyPos, afterConsequencePos)

		// 5. Handle alternative (else) branch if present
		if node.Alternative == nil {
			// No else branch: emit NULL for consistent stack behavior
			c.emit(code.OpNull)
		} else {
			err := c.Compile(node.Alternative)
			if err != nil {
				return err
			}

			if c.lastInstructionIs(code.OpPop) {
				c.removeLastPop()
			}
		}
		// Update unconditional jump target
		// Now we know where the if expression ends
		afterAlternativePos := len(c.currentInstructions())
		c.changeOperand(jumpPos, afterAlternativePos)

	case *ast.BlockStatement:
		for _, s := range node.Statements {
			err := c.Compile(s)
			if err != nil {
				return err
			}
		}
	case *ast.PrefixExpression:
		err := c.Compile(node.Right)
		if err != nil {
			return err
		}

		switch node.Operator {
		case "!":
			c.emit(code.OpBang)
		case "-":
			c.emit(code.OpMinus)
		default:
			return fmt.Errorf("unknown operator %s", node.Operator)
		}

	case *ast.InfixExpression:

		if node.Operator == "<" {
			err := c.Compile(node.Right)
			if err != nil {
				return err
			}

			err = c.Compile(node.Left)
			if err != nil {
				return err
			}

			c.emit(code.OpGreaterThan)
			return nil
		}

		// Compile left operand first
		err := c.Compile(node.Left)
		if err != nil {
			return err
		}

		// Compile right operand
		err = c.Compile(node.Right)
		if err != nil {
			return err
		}

		switch node.Operator {
		case "+":
			c.emit(code.OpAdd)
		case "-":
			c.emit(code.OpSub)
		case "*":
			c.emit(code.OpMul)
		case "/":
			c.emit(code.OpDiv)
		case ">":
			c.emit(code.OpGreaterThan)
		case "==":
			c.emit(code.OpEqual)
		case "!=":
			c.emit(code.OpNotEqual)
		default:
			return fmt.Errorf("unknown operator %s", node.Operator)
		}

	case *ast.IntegerLiteral:
		// Create an integer object for the constant pool
		integer := &object.Integer{Value: node.Value}
		// Emit instruction to load constant
		c.emit(code.OpConstant, c.addConstant(integer))

	case *ast.IndexExpression:
		err := c.Compile(node.Left)
		if err != nil {
			return err
		}

		err = c.Compile(node.Index)
		if err != nil {
			return err
		}

		c.emit(code.OpIndex)

	case *ast.FunctionLiteral:
		c.enterScope()

		for _, p := range node.Parameters {
			c.symbolTable.Define(p.Value)
		}

		err := c.Compile(node.Body)
		if err != nil {
			return err
		}

		if c.lastInstructionIs(code.OpPop) {
			c.replaceLastPopWithReturn()
		}

		if !c.lastInstructionIs(code.OpReturnValue) {
			c.emit(code.OpReturn)
		}

		// Take the current symbol table's definitions before leavinf the scope
		numLocals := c.symbolTable.numDefinitions
		instructions := c.leaveScope()

		compiledFn := &object.CompiledFunction{Instructions: instructions, NumLocals: numLocals, NumParameters: len(node.Parameters)}
		c.emit(code.OpConstant, c.addConstant(compiledFn))

	case *ast.ReturnStatement:
		err := c.Compile(node.ReturnValue)
		if err != nil {
			return err
		}

		c.emit(code.OpReturnValue)

	case *ast.CallExpression:
		err := c.Compile(node.Function)
		if err != nil {
			return err
		}

		for _, a := range node.Arguments {
			err := c.Compile(a)

			if err != nil {
				return err
			}
		}

		c.emit(code.OpCall, len(node.Arguments))
	}

	return nil
}

// Appends the given object to the end of the compilers "constants" slice
// and give it its very own identifier by returning its index in the slice.
// This identifier will now be used as the operand for the "OpConstant" instruction
// that should cause the VM to load this constant from the "constants" pool on to the stack.
func (c *Compiler) addConstant(obj object.Object) int {
	c.constants = append(c.constants, obj)
	return len(c.constants) - 1
}

// Returns the current compilation result.
// This includes both the generated instructions and constant pool
func (c *Compiler) Bytecode() *Bytecode {
	return &Bytecode{
		Instructions: c.currentInstructions(),
		Constants:    c.constants,
	}
}

// "emit" is compiler-speack for "generate" and "output". It translates to: generate an instruction and it to results,
// either by printing it, writing it to a file or by adding to a collection in memory. Collecting in memory is what we're doing.
// It returns the starting position of the just-emitted instruction.
func (c *Compiler) emit(op code.Opcode, operands ...int) int {
	ins := code.Make(op, operands...)
	pos := c.addInstruction(ins)

	c.setLastInstruction(op, pos)
	return pos
}

// Updates the compiler's instruction tracking.
// It maintains a history of the last two instructions emmitted
// Paraeters:
// - op: The opcode of the new instruction
// - pos: The position of the new instruction in the bytecode
// Used for:
// - Optimizing jump instructions
// - Managing conditional branching
// - Tracking instruction sequences for optimization
func (c *Compiler) setLastInstruction(op code.Opcode, pos int) {
	previous := c.scopes[c.scopeIndex].lastInstruction
	last := EmittedInstruction{OpCode: op, Position: pos}

	c.scopes[c.scopeIndex].previousInstruction = previous
	c.scopes[c.scopeIndex].lastInstruction = last
}

// Appends new bytecode instructions to the compiler's output
// Parameters:
// - ins: Byte slice containing the new instruction and its operands
// Returns:
// - The starting position of the newly added instruction
// Used for:
// - Building the final bytecode sequence
// - Tracking instruction positions for jumps and branches
func (c *Compiler) addInstruction(ins []byte) int {
	posNewInstruction := len(c.currentInstructions())
	updatedInstructions := append(c.currentInstructions(), ins...)

	c.scopes[c.scopeIndex].instructions = updatedInstructions
	return posNewInstruction
}

// Checks whether the opcode of the last instruction is "OpPop"
func (c *Compiler) lastInstructionIs(op code.Opcode) bool {
	if len(c.currentInstructions()) == 0 {
		return false
	}

	return c.scopes[c.scopeIndex].lastInstruction.OpCode == op
}

// Removes the last emmitted OpPop instruction
// Shortens "c.instructions" to cut off the last instruction.
func (c *Compiler) removeLastPop() {
	last := c.scopes[c.scopeIndex].lastInstruction
	previous := c.scopes[c.scopeIndex].previousInstruction

	old := c.currentInstructions()
	new := old[:last.Position]

	c.scopes[c.scopeIndex].instructions = new
	c.scopes[c.scopeIndex].lastInstruction = previous

}

// Overwrites an existing instruction at a given position
// Parameters:
// - pos: Position in bytecode to replace
// - newInstruction: The new instruction bytes
// Used for:
// - Backpatching jump address
// - Optimizing instruction sequences
// - Modifying previously emitted instructions
func (c *Compiler) replaceInstruction(pos int, newInstruction []byte) {
	ins := c.currentInstructions()
	for i := 0; i < len(newInstruction); i++ {
		ins[pos+i] = newInstruction[i]
	}
}

func (c *Compiler) enterScope() {
	scope := CompilationScope{
		instructions:        code.Instructions{},
		lastInstruction:     EmittedInstruction{},
		previousInstruction: EmittedInstruction{},
	}
	c.scopes = append(c.scopes, scope)
	c.scopeIndex++
	c.symbolTable = NewEnclosedSymbolTable(c.symbolTable)
}

func (c *Compiler) leaveScope() code.Instructions {
	instructions := c.currentInstructions()

	c.scopes = c.scopes[:len(c.scopes)-1]
	c.scopeIndex--

	c.symbolTable = c.symbolTable.Outer
	return instructions
}

// Modifies the operand of an existing instruction
// Parameters:
// - opPos: Position of the instruction to modify
// - operand: New operand value
// Used for:
// - Updating jump targets
// - Modifying constant indices
// - Fixing up forward references
func (c *Compiler) changeOperand(opPos int, operand int) {
	op := code.Opcode(c.currentInstructions()[opPos])
	newInstruction := code.Make(op, operand)

	c.replaceInstruction(opPos, newInstruction)
}

// Returns the Instructions for the current scope.
// It accesses the instructions from the compiler's current scope index
// in the scopes slice.
func (c *Compiler) currentInstructions() code.Instructions {
	return c.scopes[c.scopeIndex].instructions
}

func (c *Compiler) replaceLastPopWithReturn() {
	lastPos := c.scopes[c.scopeIndex].lastInstruction.Position
	c.replaceInstruction(lastPos, code.Make(code.OpReturnValue))

	c.scopes[c.scopeIndex].lastInstruction.OpCode = code.OpReturnValue
}
