package compiler

import (
	"fmt"
	"gibbon-lang/src/gibbon/ast"
	"gibbon-lang/src/gibbon/code"
	"gibbon-lang/src/gibbon/object"
)

/*
Compiler Implementation for the Gibbon Programming Language
-----------------------------------------------------------

This file implements the compiler that transforms AST nodes into bytecode.
The compiler acts a bridge between the parser and virtual machine, converting
high-level syntax into efficient bytecode instructions.

Key Components:
--------------

1. Compiler Structure
   - Maintains instruction sequence
   - Manages constant pool
   - Handles symbol table

2. Bytecode Structure
   - Stores compiled instructions
   - Contains constant pool
   - Ready for VM execution

3. Compilation Process
   - Walks the AST
   - Generates appropriate bytecode
   - Manages constants and symbols
*/

// Compiler transforms AST nodes into bytecode instructions.
// It maintains state during the compilation process including genrated
// instructions and constants/
type Compiler struct {
	instructions code.Instructions // Holds the generated bytecode sequence
	constants    []object.Object   // Stores all constant values encountered during compilation
}

// Represents the final output of compilation
// It contains everything the VM needs to execute the program.
type Bytecode struct {
	Instructions code.Instructions // The sequence of bytecode instructions
	Constants    []object.Object   // The constant pool containing all constant values referenced by the instructions
}

// Creates and inits a new Compiler instance
func New() *Compiler {
	return &Compiler{
		instructions: code.Instructions{},
		constants:    []object.Object{},
	}
}

/*
Processes an AST node and generates corresponding bytecode instructions.
This is the core compilation method that walks through the AST and transforms high-level
language constructs into low-level bytecode operations.

Detailed Operation:
------------------
1. AST Traversal
  - Uses type switches for different node types
  - Recursively processes nested nodes
  - Maintains correct evaluation order

2. Code Generation:
  - Emits appropriate bytecode instructions
  - Manages constant pool entries
  - Preserves expression semantics

3. Error Handling
  - Propagates errors up the compilation chain
  - Ensures partial compilation results are valid
  - Prevents invalid bytecode generation

Parameters:

	node:  The AST node to compile

Returns:

	error: Any error encountered during compilation

Example Flow:
------------
For expression "1" + "2":
1. Compile left(1):
  - Add 1 to constant pool
  - Emit OpConstant for 1

2. Compile right(2):
  - Add 2 to constant pool
  - Emit OpConstant for 2
*/
func (c *Compiler) Compile(node ast.Node) error {
	switch node := node.(type) {
	case *ast.Program:
		// Process each statement in the program sequentially
		for _, s := range node.Statements {
			err := c.Compile(s)
			if err != nil {
				return err
			}
		}

	case *ast.ExpressionStatement:
		// Compile the expression within the statement
		err := c.Compile(node.Expression)
		if err != nil {
			return err
		}
		c.emit(code.OpPop)

	case *ast.Boolean:
		if node.Value {
			c.emit(code.OpTrue)
		} else {
			c.emit(code.OpFalse)
		}

	case *ast.PrefixExpression:
		err := c.Compile(node.Right)
		if err != nil {
			return err
		}

		switch node.Operator {
		case "!":
			c.emit(code.OpBang)
		case "-":
			c.emit(code.OpMinus)
		default:
			return fmt.Errorf("unknown operator %s", node.Operator)
		}

	case *ast.InfixExpression:

		if node.Operator == "<" {
			err := c.Compile(node.Right)
			if err != nil {
				return err
			}

			err = c.Compile(node.Left)
			if err != nil {
				return err
			}

			c.emit(code.OpGreaterThan)
			return nil
		}

		// Compile left operand first
		err := c.Compile(node.Left)
		if err != nil {
			return err
		}

		// Compile right operand
		err = c.Compile(node.Right)
		if err != nil {
			return err
		}

		switch node.Operator {
		case "+":
			c.emit(code.OpAdd)
		case "-":
			c.emit(code.OpSub)
		case "*":
			c.emit(code.OpMul)
		case "/":
			c.emit(code.OpDiv)
		case ">":
			c.emit(code.OpGreaterThan)
		case "==":
			c.emit(code.OpEqual)
		case "!=":
			c.emit(code.OpNotEqual)
		default:
			return fmt.Errorf("unknown operator %s", node.Operator)
		}

	case *ast.IntegerLiteral:
		// Create an integer object for the constant pool
		integer := &object.Integer{Value: node.Value}
		// Emit instruction to load constant
		c.emit(code.OpConstant, c.addConstant(integer))
	}

	return nil
}

// Appends the given object to the end of the compilers "constants" slice
// and give it its very own identifier by returning its index in the slice.
// This identifier will now be used as the operand for the "OpConstant" instruction
// that should cause the VM to load this constant from the "constants" pool on to the stack.
func (c *Compiler) addConstant(obj object.Object) int {
	c.constants = append(c.constants, obj)
	return len(c.constants) - 1
}

// Returns the current compilation result.
// This includes both the generated instructions and constant pool
func (c *Compiler) Bytecode() *Bytecode {
	return &Bytecode{
		Instructions: c.instructions,
		Constants:    c.constants,
	}
}

// "emit" is compiler-speack for "generate" and "output". It translates to: generate an instruction and it to results,
// either by printing it, writing it to a file or by adding to a collection in memory. Collecting in memory is what we're doing.
// It returns the starting position of the just-emitted instruction.
func (c *Compiler) emit(op code.Opcode, operands ...int) int {
	ins := code.Make(op, operands...)
	pos := c.addInstruction(ins)
	return pos
}

func (c *Compiler) addInstruction(ins []byte) int {
	posNewInstruction := len(c.instructions)
	c.instructions = append(c.instructions, ins...)
	return posNewInstruction
}
